/**
 * Created by KU313880 on 3/28/2017.
 */
[
    {
        "embosserName":"ZZYYYYXXZZZZYYZXX",
        "responseCardNumber":5338,
        "currentBalance":"0.79",
        "cardType":"S",
        "cardStatus":true,
        "cardCashLimit":0,
        "lastPaymentDate":"12112017",
        "thankYouPoints":150
    },
    {
        "embosserName":"ZZYYYYXXZZZZYYZXX",
        "responseCardNumber":5338,
        "currentBalance":"0.79",
        "cardType":"S",
        "cardStatus":false,
        "cardCashLimit":0,
        "lastPaymentDate":"12112017",
        "thankYouPoints":150
    }
]